# Cloudflare Pages configuration
name = "techwithdikshant"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "18"

[env.production]
# Add any production environment variables here if needed