

name = "techwithdikshant"
compatibility_date = "2024-08-25"
pages_build_output_dir = "dist"

[pages]
# Disable functions by pointing to an empty/nonexistent dir
# (prevents Wrangler from looking into /functions)
functions = ""
