# Cloudflare Pages configuration
name = "techwithdikshant"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "/"
destination = "dist"

[build.environment_variables]
NODE_VERSION = "18"

[[build.environment_variables]]
SKIP_DEPENDENCY_INSTALL = "true"

[env.production]
# Add any production environment variables here if needed